services:
  mysqldb:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_booking_db
    ports:
      - "3310:3306"   # CHANGED PORT
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  backend:
    image: likithareddy25/hotel-backend   # FIXED
    container_name: springboot
    ports:
      - "5055:2000"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    image: likithareddy25/hotel-frontend  # FIXED
    container_name: react
    ports:
      - "5056:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net:
